[target.mipsel-sony-psp.dependencies.core]
[target.mipsel-sony-psp.dependencies.alloc]
[target.mipsel-sony-psp.dependencies.panic_unwind]
stage = 1

[patch.crates-io.libc]
git = "https://github.com/overdrivenpotato/libc"
branch = "psp"
