[package]
name = "psp-rand-example"
version = "0.1.0"
authors = ["Marko Mijalkovic <marko.mijalkovic97@gmail.com>"]
edition = "2018"

[dependencies]
psp = { path = "../../psp", features = ["rand_core"] }
