[target.psp.dependencies.core]
[target.psp.dependencies.alloc]
[target.psp.dependencies.panic_unwind]
stage = 1

[patch.crates-io.libc]
git = "https://github.com/overdrivenpotato/libc"
branch = "psp"

[patch.crates-io.core]
git = "https://github.com/overdrivenpotato/libcore-psp"
